# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: kontractor
services:
  mongodb:
    extends:
      file: ./mongodb.yml
      service: mongodb
  redis:
    extends:
      file: ./redis.yml
      service: redis
